logging:
  level:
    top:
      pofengsystem: debug
    io:
      netty:
        handler:
          logging:
            LoggingHandler: debug
spring:
  redis:
    #    host: 192.168.50.60
    host: localhost
    port: 6379
    database: 0
  profiles:
    active: redis
